<img src="https://www.northumbria.ac.uk/-/media/40f0efdb3a6745fda5b0d982d53b8cd9.ashx" alt="Northumbria University"/>

---

 
### KF7029 MSc Computer Science and Digital Technologies Project

Dissertation project title:
# How Machine Learning (ML) can improve Business?

---
**Student ID:** W19052374

**Student Name:** Rohit Karanam

---

**Supervisor Name	:** 

**Second Marker Name	:** 

---

# CH-1 Configration

##  Dataset
Brazilian E-Commerce data
https://www.kaggle.com/code/santiagorcastro/3-insights-on-olist-dataset-brazilian-ecommerce/data

## Python packages

In [1]:
## install
#!pip install numpy

In [2]:
## import

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

# CH-2 Dataset

In [3]:
# file path
lc_root="./Brazilian E-Commerce/"
lc_review="olist_order_reviews_dataset.csv"
lc_orders="olist_orders_dataset.csv"
lc_order_products="olist_order_items_dataset.csv"
lc_products="olist_products_dataset.csv"
lc_customers="olist_customers_dataset.csv"
lc_geolocation="olist_geolocation_dataset.csv"

In [4]:
def load_dataset(file, columns):
    path= lc_root + file
    data=pd.read_csv(path,names=columns, header=0)
    print(f'Total rows:{data.shape[0]} and columns:{data.shape[1]} for {file}')   
    return data

In [5]:
dt_review=load_dataset(
    lc_review,
    ["review_id","order_id","review_score","review_comment_title","review_comment_message","review_creation_date","review_answer_timestamp"]
)

dt_orders=load_dataset(
    lc_orders,
    ["order_id","customer_id","order_status","order_purchase_timestamp","order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date"]
)

dt_order_products=load_dataset(
    lc_order_products,
    ["order_id","order_item_id","product_id","seller_id","shipping_limit_date","price","freight_value"]
)

dt_products=load_dataset(
    lc_products,
    ["product_id","product_category_name","product_name_lenght","product_description_lenght","product_photos_qty","product_weight_g","product_length_cm","product_height_cm","product_width_cm"]
)
lc_customers

dt_customers=load_dataset(
    lc_customers,
    ["customer_id","customer_unique_id","customer_zip_code_prefix","customer_city","customer_state"]
)
dt_geolocation=load_dataset(
    lc_geolocation,
    ["geolocation_zip_code_prefix","geolocation_lat","geolocation_lng","geolocation_city","geolocation_state"]
)

Total rows:99224 and columns:7 for olist_order_reviews_dataset.csv
Total rows:99441 and columns:8 for olist_orders_dataset.csv
Total rows:112650 and columns:7 for olist_order_items_dataset.csv
Total rows:32951 and columns:9 for olist_products_dataset.csv
Total rows:99441 and columns:5 for olist_customers_dataset.csv
Total rows:1000163 and columns:5 for olist_geolocation_dataset.csv

# CH-3 Pre-processing

In [6]:
# Remove unused columns
dt_orders = dt_orders[['order_id','customer_id','order_purchase_timestamp']]
dt_order_products = dt_order_products[['order_id','order_item_id','product_id','price']]
dt_products = dt_products[["product_id","product_category_name"]]
dt_review = dt_review[["review_id","order_id","review_score","review_comment_title","review_comment_message","review_creation_date"]]
dt_customers = dt_customers[["customer_id","customer_city","customer_state","customer_zip_code_prefix"]]
dt_geolocation = dt_geolocation[["geolocation_zip_code_prefix","geolocation_lat","geolocation_lng","geolocation_city","geolocation_state"]]

In [7]:
# Change column type
dt_orders['order_id']=dt_orders['order_id'].astype(str)
dt_orders['customer_id']=dt_orders['customer_id'].astype(str)
dt_order_products['order_id']=dt_order_products['order_id'].astype(str)
dt_order_products['product_id']=dt_order_products['product_id'].astype(str)
dt_products['product_id']=dt_products['product_id'].astype(str)
dt_review['order_id']=dt_order_products['order_id'].astype(str)
dt_customers['customer_id']=dt_customers['customer_id'].astype(str)

In [8]:
# rename column
dt_customers = dt_customers.rename(columns={'customer_zip_code_prefix':'zip_code'})
dt_geolocation = dt_geolocation.rename(columns={'geolocation_zip_code_prefix':'zip_code'})

In [9]:
# merge datasets
dt_main=pd.merge(dt_orders, dt_order_products, on = 'order_id')
dt_main=pd.merge(dt_main, dt_review, on = 'order_id')
dt_main=pd.merge(dt_main, dt_products, on = 'product_id')
dt_main=pd.merge(dt_main, dt_customers, on = 'customer_id')
dt_main=pd.merge(dt_main, dt_geolocation, on = 'zip_code')
dt_main

,order_id,customer_id,order_purchase_timestamp,order_item_id,product_id,price,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,product_category_name,customer_city,customer_state,zip_code,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,1,595fac2a385ac33a80bd5114aec74eb8,118.7,ee003f7cabb1176c9825101bae3fe4f2,5,NaN,NaN,2017-12-19 00:00:00,perfumaria,barreiras,BA,47813,-12.169860,-44.988369,barreiras,BA
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,1,595fac2a385ac33a80bd5114aec74eb8,118.7,ee003f7cabb1176c9825101bae3fe4f2,5,NaN,NaN,2017-12-19 00:00:00,perfumaria,barreiras,BA,47813,-12.126669,-45.016167,barreiras,BA
2,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,1,595fac2a385ac33a80bd5114aec74eb8,118.7,ee003f7cabb1176c9825101bae3fe4f2,5,NaN,NaN,2017-12-19 00:00:00,perfumaria,barreiras,BA,47813,-12.128049,-45.008985,barreiras,BA
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,1,595fac2a385ac33a80bd5114aec74eb8,118.7,ee003f7cabb1176c9825101bae3fe4f2,5,NaN,NaN,2017-12-19 00:00:00,perfumaria,barreiras,BA,47813,-12.126651,-45.016161,barreiras,BA
4,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,1,595fac2a385ac33a80bd5114aec74eb8,118.7,ee003f7cabb1176c9825101bae3fe4f2,5,NaN,NaN,2017-12-19 00:00:00,perfumaria,barreiras,BA,47813,-12.125107,-45.008162,barreiras,BA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21308769,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,2017-12-20 09:52:41,1,3d2c44374ee42b3003a470f3e937a2ea,55.9,0efcd808a613ce99a76d6891bca5b142,1,NaN,NaN,2018-05-17 00:00:00,instrumentos_musicais,campo do tenente,PR,83870,-25.976613,-49.682770,campo do tenente,PR
21308770,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,2017-12-20 09:52:41,1,3d2c44374ee42b3003a470f3e937a2ea,55.9,0efcd808a613ce99a76d6891bca5b142,1,NaN,NaN,2018-05-17 00:00:00,instrumentos_musicais,campo do tenente,PR,83870,-25.984320,-49.685323,campo do tenente,PR
21308771,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,2017-12-20 09:52:41,1,3d2c44374ee42b3003a470f3e937a2ea,55.9,0efcd808a613ce99a76d6891bca5b142,1,NaN,NaN,2018-05-17 00:00:00,instrumentos_musicais,campo do tenente,PR,83870,-25.981080,-49.682970,campo do tenente,PR
21308772,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,2017-12-20 09:52:41,1,3d2c44374ee42b3003a470f3e937a2ea,55.9,0efcd808a613ce99a76d6891bca5b142,1,NaN,NaN,2018-05-17 00:00:00,instrumentos_musicais,campo do tenente,PR,83870,-25.981102,-49.682042,campo do tenente,PR
21308773,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,2017-12-20 09:52:41,1,3d2c44374ee42b3003a470f3e937a2ea,55.9,0efcd808a613ce99a76d6891bca5b142,1,NaN,NaN,2018-05-17 00:00:00,instrumentos_musicais,campo do tenente,PR,83870,-25.986294,-49.684537,campo do tenente,PR

In [10]:
# count number of duplicate rows
# Remove duplicate entires
print('Total duplicate records:',dt_main.duplicated().sum())
dt_main.drop_duplicates(inplace=True)

Total duplicate records: 6770723

In [11]:
dt_main['month']=dt_main['order_purchase_timestamp'].str[0:7]

In [12]:
# Convert data type
dt_main['order_purchase_timestamp']=pd.to_datetime(dt_main['order_purchase_timestamp'])
dt_main['geolocation_lat'] = dt_main['geolocation_lat'].astype(np.float64)
dt_main['geolocation_lng'] = dt_main['geolocation_lng'].astype(np.float64)

In [13]:
dt_main['YY'] = dt_main['order_purchase_timestamp'].dt.year 
dt_main['MM'] = dt_main['order_purchase_timestamp'].dt.month 
dt_main['DD'] = dt_main['order_purchase_timestamp'].dt.day 
dt_main['Hour'] = dt_main['order_purchase_timestamp'].dt.hour 
dt_main['Minute'] = dt_main['order_purchase_timestamp'].dt.minute

In [14]:
dt_main.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14538051 entries, 0 to 21308773
Data columns (total 25 columns):
 #   Column                    Dtype
---  ------                    -----
 0   order_id                  object
 1   customer_id               object
 2   order_purchase_timestamp  datetime64[ns]
 3   order_item_id             int64
 4   product_id                object
 5   price                     float64
 6   review_id                 object
 7   review_score              int64
 8   review_comment_title      object
 9   review_comment_message    object
 10  review_creation_date      object
 11  product_category_name     object
 12  customer_city             object
 13  customer_state            object
 14  zip_code                  int64
 15  geolocation_lat           float64
 16  geolocation_lng           float64
 17  geolocation_city          object
 18  geolocation_state         object
 19  month                     object
 20  YY                        int64
 21  MM                        int64
 22  DD                        int64
 23  Hour                      int64
 24  Minute                    int64
dtypes: datetime64[ns](1), float64(3), int64(8), object(13)
memory usage: 2.8+ GB

# CH-4 Machine Learning (ML) analysis

## Sales Forecasting

## Product Stock issue

## Business performance

## Customer review

## Sales Forecasting